# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Methods for Physics with Python.
author: Ryoichi Kawai
copyright: "Ryoichi Kawai 2023"
logo: me-tiny.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# add amslatex suppport
#parse:
#   myst_enable_extensions:
#   - amsmath

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ryoichikawai/comp-phys/ # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
   use_issues_button: true
   use_repository_button: true
   use_download_button: true
#   use_issues_button: true

sphinx:
   bibtex_reference_style: author_year
   mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
   extra_extensions:
   -  sphinx_jupyterbook_latex

launch_buttons:
   notebook_interface: "classic"
#   binderhub_url: ""
   colab_url: "https://colab.research.google.com"
#   thebe: true
