#!/usr/bin/env python
# coding: utf-8

# (chap-prerequisites)=
# # Preparation
# 
# This book is entirely written either in the Jupyter Notebook or Markdown. The online version is generated by Jupyter Book.  The first section of this chapter explains how the interactive book works.  In the following preparation sections, software used in this book and online tools are introduced.
# 
# We will use computer software, *Python and *JupyterLab*. You must train yourself as you read this book.   
# 
# The use of Python and JupyterLabis absolutely required. If you do not have your own computer or the capacity of your computer is limited, free cloud-based online services, such as *Google Colab* satisfies the requirement. Apart from some inconvenience, they work quite well.  However, it will be convenient to run codes on your computer.  Therefore, it is highly recommended to install required software on your computer.  Installation instruction is given in the following sections.

# In[ ]:




